CREATE TABLE clients (
    id BIGINT NOT NULL,
    name VARCHAR(200),
    CONSTRAINT CLIENTS_PK PRIMARY KEY(id),
    CONSTRAINT CLIENTS_NAME_MIN_LENGTH CHECK(CHAR_LENGTH(name)>=3)
);

CREATE TABLE planets (
    id VARCHAR NOT NULL,
    name VARCHAR(500),
    CONSTRAINT PLANETS_PK PRIMARY KEY(id),
    CONSTRAINT PLANETS_NAME_MIN_LENGTH CHECK(CHAR_LENGTH(name)>=1)
);

CREATE TABLE tickets (
    id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    from_planet_id VARCHAR NOT NULL,
    to_planet_id VARCHAR NOT NULL,
    CONSTRAINT TICKETS_PK PRIMARY KEY(id),
    CONSTRAINT TICKETS_CLIENTS_FK FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT TICKETS_PLANETS_FROM_FK FOREIGN KEY (from_planet_id) REFERENCES planets(id),
    CONSTRAINT TICKETS_PLANETS_to_FK FOREIGN KEY (to_planet_id) REFERENCES planets(id)
);

CREATE SEQUENCE clients_sequence START WITH 100;
CREATE SEQUENCE tickets_sequence START WITH 100;

ALTER TABLE clients ALTER COLUMN ID SET DEFAULT NEXTVAL('clients_sequence');
ALTER TABLE tickets ALTER COLUMN ID SET DEFAULT NEXTVAL('tickets_sequence');